/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __JSONITE_WIDGET_H__
#define __JSONITE_WIDGET_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.jsoniteDaemon.Konfabulator.Widget */

#define TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET (com_jsonite_daemon_konfabulator_widget_get_type ())
#define COM_JSONITE_DAEMON_KONFABULATOR_WIDGET(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET, ComJsoniteDaemonKonfabulatorWidget))
#define IS_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET))
#define COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET, ComJsoniteDaemonKonfabulatorWidgetIface))

struct _ComJsoniteDaemonKonfabulatorWidget;
typedef struct _ComJsoniteDaemonKonfabulatorWidget ComJsoniteDaemonKonfabulatorWidget;
typedef struct _ComJsoniteDaemonKonfabulatorWidgetIface ComJsoniteDaemonKonfabulatorWidgetIface;

struct _ComJsoniteDaemonKonfabulatorWidgetIface
{
    GTypeInterface parent_iface;


    gboolean (*handle_create_image) (
            ComJsoniteDaemonKonfabulatorWidget *object,
            GDBusMethodInvocation *invocation,
            const gchar *arg_src,
            const gchar *arg_name,
            gint arg_hOffset,
            gint arg_vOffset,
            const gchar *arg_alignment);

    gboolean (*handle_create_text) (
            ComJsoniteDaemonKonfabulatorWidget *object,
            GDBusMethodInvocation *invocation,
            const gchar *arg_data,
            guint arg_size,
            const gchar *arg_style,
            const gchar *arg_name,
            gint arg_hOffset,
            gint arg_vOffset,
            const gchar *arg_alignment);

    gboolean (*handle_create_window) (
            ComJsoniteDaemonKonfabulatorWidget *object,
            GDBusMethodInvocation *invocation,
            const gchar *arg_title,
            const gchar *arg_name,
            guint arg_width,
            guint arg_height);

    gboolean (*handle_show_all_settings) (
            ComJsoniteDaemonKonfabulatorWidget *object,
            GDBusMethodInvocation *invocation);

    const gchar * (*get_debug) (ComJsoniteDaemonKonfabulatorWidget *object);

    const gchar * (*get_image_alignment) (ComJsoniteDaemonKonfabulatorWidget *object);

    gint  (*get_image_hoffset) (ComJsoniteDaemonKonfabulatorWidget *object);

    const gchar * (*get_image_name) (ComJsoniteDaemonKonfabulatorWidget *object);

    const gchar * (*get_image_src) (ComJsoniteDaemonKonfabulatorWidget *object);

    gint  (*get_image_voffset) (ComJsoniteDaemonKonfabulatorWidget *object);

    const gchar * (*get_text_alignment) (ComJsoniteDaemonKonfabulatorWidget *object);

    const gchar * (*get_text_data) (ComJsoniteDaemonKonfabulatorWidget *object);

    gint  (*get_text_hoffset) (ComJsoniteDaemonKonfabulatorWidget *object);

    const gchar * (*get_text_name) (ComJsoniteDaemonKonfabulatorWidget *object);

    guint  (*get_text_size) (ComJsoniteDaemonKonfabulatorWidget *object);

    const gchar * (*get_text_style) (ComJsoniteDaemonKonfabulatorWidget *object);

    gint  (*get_text_voffset) (ComJsoniteDaemonKonfabulatorWidget *object);

    guint  (*get_window_height) (ComJsoniteDaemonKonfabulatorWidget *object);

    const gchar * (*get_window_name) (ComJsoniteDaemonKonfabulatorWidget *object);

    const gchar * (*get_window_title) (ComJsoniteDaemonKonfabulatorWidget *object);

    guint  (*get_window_width) (ComJsoniteDaemonKonfabulatorWidget *object);

};

GType com_jsonite_daemon_konfabulator_widget_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *com_jsonite_daemon_konfabulator_widget_interface_info (void);
guint com_jsonite_daemon_konfabulator_widget_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void com_jsonite_daemon_konfabulator_widget_complete_create_window (
        ComJsoniteDaemonKonfabulatorWidget *object,
        GDBusMethodInvocation *invocation);

void com_jsonite_daemon_konfabulator_widget_complete_create_image (
        ComJsoniteDaemonKonfabulatorWidget *object,
        GDBusMethodInvocation *invocation);

void com_jsonite_daemon_konfabulator_widget_complete_create_text (
        ComJsoniteDaemonKonfabulatorWidget *object,
        GDBusMethodInvocation *invocation);

void com_jsonite_daemon_konfabulator_widget_complete_show_all_settings (
        ComJsoniteDaemonKonfabulatorWidget *object,
        GDBusMethodInvocation *invocation,
        const gchar *jsonConfig);



/* D-Bus method calls: */
void com_jsonite_daemon_konfabulator_widget_call_create_window (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        const gchar *arg_title,
        const gchar *arg_name,
        guint arg_width,
        guint arg_height,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean com_jsonite_daemon_konfabulator_widget_call_create_window_finish (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        GAsyncResult *res,
        GError **error);

gboolean com_jsonite_daemon_konfabulator_widget_call_create_window_sync (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        const gchar *arg_title,
        const gchar *arg_name,
        guint arg_width,
        guint arg_height,
        GCancellable *cancellable,
        GError **error);

void com_jsonite_daemon_konfabulator_widget_call_create_image (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        const gchar *arg_src,
        const gchar *arg_name,
        gint arg_hOffset,
        gint arg_vOffset,
        const gchar *arg_alignment,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean com_jsonite_daemon_konfabulator_widget_call_create_image_finish (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        GAsyncResult *res,
        GError **error);

gboolean com_jsonite_daemon_konfabulator_widget_call_create_image_sync (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        const gchar *arg_src,
        const gchar *arg_name,
        gint arg_hOffset,
        gint arg_vOffset,
        const gchar *arg_alignment,
        GCancellable *cancellable,
        GError **error);

void com_jsonite_daemon_konfabulator_widget_call_create_text (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        const gchar *arg_data,
        guint arg_size,
        const gchar *arg_style,
        const gchar *arg_name,
        gint arg_hOffset,
        gint arg_vOffset,
        const gchar *arg_alignment,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean com_jsonite_daemon_konfabulator_widget_call_create_text_finish (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        GAsyncResult *res,
        GError **error);

gboolean com_jsonite_daemon_konfabulator_widget_call_create_text_sync (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        const gchar *arg_data,
        guint arg_size,
        const gchar *arg_style,
        const gchar *arg_name,
        gint arg_hOffset,
        gint arg_vOffset,
        const gchar *arg_alignment,
        GCancellable *cancellable,
        GError **error);

void com_jsonite_daemon_konfabulator_widget_call_show_all_settings (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean com_jsonite_daemon_konfabulator_widget_call_show_all_settings_finish (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        gchar **out_jsonConfig,
        GAsyncResult *res,
        GError **error);

gboolean com_jsonite_daemon_konfabulator_widget_call_show_all_settings_sync (
        ComJsoniteDaemonKonfabulatorWidget *proxy,
        gchar **out_jsonConfig,
        GCancellable *cancellable,
        GError **error);



/* D-Bus property accessors: */
const gchar *com_jsonite_daemon_konfabulator_widget_get_debug (ComJsoniteDaemonKonfabulatorWidget *object);
gchar *com_jsonite_daemon_konfabulator_widget_dup_debug (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_debug (ComJsoniteDaemonKonfabulatorWidget *object, const gchar *value);

const gchar *com_jsonite_daemon_konfabulator_widget_get_window_name (ComJsoniteDaemonKonfabulatorWidget *object);
gchar *com_jsonite_daemon_konfabulator_widget_dup_window_name (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_window_name (ComJsoniteDaemonKonfabulatorWidget *object, const gchar *value);

const gchar *com_jsonite_daemon_konfabulator_widget_get_window_title (ComJsoniteDaemonKonfabulatorWidget *object);
gchar *com_jsonite_daemon_konfabulator_widget_dup_window_title (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_window_title (ComJsoniteDaemonKonfabulatorWidget *object, const gchar *value);

guint com_jsonite_daemon_konfabulator_widget_get_window_width (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_window_width (ComJsoniteDaemonKonfabulatorWidget *object, guint value);

guint com_jsonite_daemon_konfabulator_widget_get_window_height (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_window_height (ComJsoniteDaemonKonfabulatorWidget *object, guint value);

const gchar *com_jsonite_daemon_konfabulator_widget_get_image_src (ComJsoniteDaemonKonfabulatorWidget *object);
gchar *com_jsonite_daemon_konfabulator_widget_dup_image_src (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_image_src (ComJsoniteDaemonKonfabulatorWidget *object, const gchar *value);

const gchar *com_jsonite_daemon_konfabulator_widget_get_image_name (ComJsoniteDaemonKonfabulatorWidget *object);
gchar *com_jsonite_daemon_konfabulator_widget_dup_image_name (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_image_name (ComJsoniteDaemonKonfabulatorWidget *object, const gchar *value);

gint com_jsonite_daemon_konfabulator_widget_get_image_hoffset (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_image_hoffset (ComJsoniteDaemonKonfabulatorWidget *object, gint value);

gint com_jsonite_daemon_konfabulator_widget_get_image_voffset (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_image_voffset (ComJsoniteDaemonKonfabulatorWidget *object, gint value);

const gchar *com_jsonite_daemon_konfabulator_widget_get_image_alignment (ComJsoniteDaemonKonfabulatorWidget *object);
gchar *com_jsonite_daemon_konfabulator_widget_dup_image_alignment (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_image_alignment (ComJsoniteDaemonKonfabulatorWidget *object, const gchar *value);

const gchar *com_jsonite_daemon_konfabulator_widget_get_text_data (ComJsoniteDaemonKonfabulatorWidget *object);
gchar *com_jsonite_daemon_konfabulator_widget_dup_text_data (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_text_data (ComJsoniteDaemonKonfabulatorWidget *object, const gchar *value);

guint com_jsonite_daemon_konfabulator_widget_get_text_size (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_text_size (ComJsoniteDaemonKonfabulatorWidget *object, guint value);

const gchar *com_jsonite_daemon_konfabulator_widget_get_text_style (ComJsoniteDaemonKonfabulatorWidget *object);
gchar *com_jsonite_daemon_konfabulator_widget_dup_text_style (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_text_style (ComJsoniteDaemonKonfabulatorWidget *object, const gchar *value);

const gchar *com_jsonite_daemon_konfabulator_widget_get_text_name (ComJsoniteDaemonKonfabulatorWidget *object);
gchar *com_jsonite_daemon_konfabulator_widget_dup_text_name (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_text_name (ComJsoniteDaemonKonfabulatorWidget *object, const gchar *value);

gint com_jsonite_daemon_konfabulator_widget_get_text_hoffset (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_text_hoffset (ComJsoniteDaemonKonfabulatorWidget *object, gint value);

gint com_jsonite_daemon_konfabulator_widget_get_text_voffset (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_text_voffset (ComJsoniteDaemonKonfabulatorWidget *object, gint value);

const gchar *com_jsonite_daemon_konfabulator_widget_get_text_alignment (ComJsoniteDaemonKonfabulatorWidget *object);
gchar *com_jsonite_daemon_konfabulator_widget_dup_text_alignment (ComJsoniteDaemonKonfabulatorWidget *object);
void com_jsonite_daemon_konfabulator_widget_set_text_alignment (ComJsoniteDaemonKonfabulatorWidget *object, const gchar *value);


/* ---- */

#define TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY (com_jsonite_daemon_konfabulator_widget_proxy_get_type ())
#define COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY, ComJsoniteDaemonKonfabulatorWidgetProxy))
#define COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY, ComJsoniteDaemonKonfabulatorWidgetProxyClass))
#define COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY, ComJsoniteDaemonKonfabulatorWidgetProxyClass))
#define IS_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY))
#define IS_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_PROXY))

typedef struct _ComJsoniteDaemonKonfabulatorWidgetProxy ComJsoniteDaemonKonfabulatorWidgetProxy;
typedef struct _ComJsoniteDaemonKonfabulatorWidgetProxyClass ComJsoniteDaemonKonfabulatorWidgetProxyClass;
typedef struct _ComJsoniteDaemonKonfabulatorWidgetProxyPrivate ComJsoniteDaemonKonfabulatorWidgetProxyPrivate;

struct _ComJsoniteDaemonKonfabulatorWidgetProxy
{
    /*< private >*/
    GDBusProxy parent_instance;
    ComJsoniteDaemonKonfabulatorWidgetProxyPrivate *priv;
};

struct _ComJsoniteDaemonKonfabulatorWidgetProxyClass
{
    GDBusProxyClass parent_class;
};

GType com_jsonite_daemon_konfabulator_widget_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComJsoniteDaemonKonfabulatorWidgetProxy, g_object_unref)
#endif

    void com_jsonite_daemon_konfabulator_widget_proxy_new (
            GDBusConnection     *connection,
            GDBusProxyFlags      flags,
            const gchar         *name,
            const gchar         *object_path,
            GCancellable        *cancellable,
            GAsyncReadyCallback  callback,
            gpointer             user_data);
ComJsoniteDaemonKonfabulatorWidget *com_jsonite_daemon_konfabulator_widget_proxy_new_finish (
        GAsyncResult        *res,
        GError             **error);
ComJsoniteDaemonKonfabulatorWidget *com_jsonite_daemon_konfabulator_widget_proxy_new_sync (
        GDBusConnection     *connection,
        GDBusProxyFlags      flags,
        const gchar         *name,
        const gchar         *object_path,
        GCancellable        *cancellable,
        GError             **error);

void com_jsonite_daemon_konfabulator_widget_proxy_new_for_bus (
        GBusType             bus_type,
        GDBusProxyFlags      flags,
        const gchar         *name,
        const gchar         *object_path,
        GCancellable        *cancellable,
        GAsyncReadyCallback  callback,
        gpointer             user_data);
ComJsoniteDaemonKonfabulatorWidget *com_jsonite_daemon_konfabulator_widget_proxy_new_for_bus_finish (
        GAsyncResult        *res,
        GError             **error);
ComJsoniteDaemonKonfabulatorWidget *com_jsonite_daemon_konfabulator_widget_proxy_new_for_bus_sync (
        GBusType             bus_type,
        GDBusProxyFlags      flags,
        const gchar         *name,
        const gchar         *object_path,
        GCancellable        *cancellable,
        GError             **error);


/* ---- */

#define TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON (com_jsonite_daemon_konfabulator_widget_skeleton_get_type ())
#define COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON, ComJsoniteDaemonKonfabulatorWidgetSkeleton))
#define COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON, ComJsoniteDaemonKonfabulatorWidgetSkeletonClass))
#define COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON, ComJsoniteDaemonKonfabulatorWidgetSkeletonClass))
#define IS_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON))
#define IS_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_JSONITE_DAEMON_KONFABULATOR_WIDGET_SKELETON))

typedef struct _ComJsoniteDaemonKonfabulatorWidgetSkeleton ComJsoniteDaemonKonfabulatorWidgetSkeleton;
typedef struct _ComJsoniteDaemonKonfabulatorWidgetSkeletonClass ComJsoniteDaemonKonfabulatorWidgetSkeletonClass;
typedef struct _ComJsoniteDaemonKonfabulatorWidgetSkeletonPrivate ComJsoniteDaemonKonfabulatorWidgetSkeletonPrivate;

struct _ComJsoniteDaemonKonfabulatorWidgetSkeleton
{
    /*< private >*/
    GDBusInterfaceSkeleton parent_instance;
    ComJsoniteDaemonKonfabulatorWidgetSkeletonPrivate *priv;
};

struct _ComJsoniteDaemonKonfabulatorWidgetSkeletonClass
{
    GDBusInterfaceSkeletonClass parent_class;
};

GType com_jsonite_daemon_konfabulator_widget_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComJsoniteDaemonKonfabulatorWidgetSkeleton, g_object_unref)
#endif

    ComJsoniteDaemonKonfabulatorWidget *com_jsonite_daemon_konfabulator_widget_skeleton_new (void);


    G_END_DECLS

#endif /* __JSONITE_WIDGET_H__ */
