/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __GDBUS_CALCULATOR_H__
#define __GDBUS_CALCULATOR_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.jsoniteDaemon.Calculator */

#define TYPE_COM_JSONITE_DAEMON_CALCULATOR (com_jsonite_daemon_calculator_get_type ())
#define COM_JSONITE_DAEMON_CALCULATOR(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_JSONITE_DAEMON_CALCULATOR, ComJsoniteDaemonCalculator))
#define IS_COM_JSONITE_DAEMON_CALCULATOR(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_JSONITE_DAEMON_CALCULATOR))
#define COM_JSONITE_DAEMON_CALCULATOR_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_COM_JSONITE_DAEMON_CALCULATOR, ComJsoniteDaemonCalculatorIface))

struct _ComJsoniteDaemonCalculator;
typedef struct _ComJsoniteDaemonCalculator ComJsoniteDaemonCalculator;
typedef struct _ComJsoniteDaemonCalculatorIface ComJsoniteDaemonCalculatorIface;

struct _ComJsoniteDaemonCalculatorIface
{
    GTypeInterface parent_iface;

    gboolean (*handle_add) (
            ComJsoniteDaemonCalculator *object,
            GDBusMethodInvocation *invocation,
            const gchar *arg_json_request);

    gboolean (*handle_divide) (
            ComJsoniteDaemonCalculator *object,
            GDBusMethodInvocation *invocation,
            const gchar *arg_json_request);

    gboolean (*handle_multiply) (
            ComJsoniteDaemonCalculator *object,
            GDBusMethodInvocation *invocation,
            const gchar *arg_json_request);

    gboolean (*handle_subtract) (
            ComJsoniteDaemonCalculator *object,
            GDBusMethodInvocation *invocation,
            const gchar *arg_json_request);

};

GType com_jsonite_daemon_calculator_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *com_jsonite_daemon_calculator_interface_info (void);
guint com_jsonite_daemon_calculator_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void com_jsonite_daemon_calculator_complete_add (
        ComJsoniteDaemonCalculator *object,
        GDBusMethodInvocation *invocation,
        const gchar *json_response);

void com_jsonite_daemon_calculator_complete_subtract (
        ComJsoniteDaemonCalculator *object,
        GDBusMethodInvocation *invocation,
        const gchar *json_response);

void com_jsonite_daemon_calculator_complete_multiply (
        ComJsoniteDaemonCalculator *object,
        GDBusMethodInvocation *invocation,
        const gchar *json_response);

void com_jsonite_daemon_calculator_complete_divide (
        ComJsoniteDaemonCalculator *object,
        GDBusMethodInvocation *invocation,
        const gchar *json_response);



/* D-Bus method calls: */
void com_jsonite_daemon_calculator_call_add (
        ComJsoniteDaemonCalculator *proxy,
        const gchar *arg_json_request,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean com_jsonite_daemon_calculator_call_add_finish (
        ComJsoniteDaemonCalculator *proxy,
        gchar **out_json_response,
        GAsyncResult *res,
        GError **error);

gboolean com_jsonite_daemon_calculator_call_add_sync (
        ComJsoniteDaemonCalculator *proxy,
        const gchar *arg_json_request,
        gchar **out_json_response,
        GCancellable *cancellable,
        GError **error);

void com_jsonite_daemon_calculator_call_subtract (
        ComJsoniteDaemonCalculator *proxy,
        const gchar *arg_json_request,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean com_jsonite_daemon_calculator_call_subtract_finish (
        ComJsoniteDaemonCalculator *proxy,
        gchar **out_json_response,
        GAsyncResult *res,
        GError **error);

gboolean com_jsonite_daemon_calculator_call_subtract_sync (
        ComJsoniteDaemonCalculator *proxy,
        const gchar *arg_json_request,
        gchar **out_json_response,
        GCancellable *cancellable,
        GError **error);

void com_jsonite_daemon_calculator_call_multiply (
        ComJsoniteDaemonCalculator *proxy,
        const gchar *arg_json_request,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean com_jsonite_daemon_calculator_call_multiply_finish (
        ComJsoniteDaemonCalculator *proxy,
        gchar **out_json_response,
        GAsyncResult *res,
        GError **error);

gboolean com_jsonite_daemon_calculator_call_multiply_sync (
        ComJsoniteDaemonCalculator *proxy,
        const gchar *arg_json_request,
        gchar **out_json_response,
        GCancellable *cancellable,
        GError **error);

void com_jsonite_daemon_calculator_call_divide (
        ComJsoniteDaemonCalculator *proxy,
        const gchar *arg_json_request,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean com_jsonite_daemon_calculator_call_divide_finish (
        ComJsoniteDaemonCalculator *proxy,
        gchar **out_json_response,
        GAsyncResult *res,
        GError **error);

gboolean com_jsonite_daemon_calculator_call_divide_sync (
        ComJsoniteDaemonCalculator *proxy,
        const gchar *arg_json_request,
        gchar **out_json_response,
        GCancellable *cancellable,
        GError **error);



/* ---- */

#define TYPE_COM_JSONITE_DAEMON_CALCULATOR_PROXY (com_jsonite_daemon_calculator_proxy_get_type ())
#define COM_JSONITE_DAEMON_CALCULATOR_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_JSONITE_DAEMON_CALCULATOR_PROXY, ComJsoniteDaemonCalculatorProxy))
#define COM_JSONITE_DAEMON_CALCULATOR_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_JSONITE_DAEMON_CALCULATOR_PROXY, ComJsoniteDaemonCalculatorProxyClass))
#define COM_JSONITE_DAEMON_CALCULATOR_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_JSONITE_DAEMON_CALCULATOR_PROXY, ComJsoniteDaemonCalculatorProxyClass))
#define IS_COM_JSONITE_DAEMON_CALCULATOR_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_JSONITE_DAEMON_CALCULATOR_PROXY))
#define IS_COM_JSONITE_DAEMON_CALCULATOR_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_JSONITE_DAEMON_CALCULATOR_PROXY))

typedef struct _ComJsoniteDaemonCalculatorProxy ComJsoniteDaemonCalculatorProxy;
typedef struct _ComJsoniteDaemonCalculatorProxyClass ComJsoniteDaemonCalculatorProxyClass;
typedef struct _ComJsoniteDaemonCalculatorProxyPrivate ComJsoniteDaemonCalculatorProxyPrivate;

struct _ComJsoniteDaemonCalculatorProxy
{
    /*< private >*/
    GDBusProxy parent_instance;
    ComJsoniteDaemonCalculatorProxyPrivate *priv;
};

struct _ComJsoniteDaemonCalculatorProxyClass
{
    GDBusProxyClass parent_class;
};

GType com_jsonite_daemon_calculator_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComJsoniteDaemonCalculatorProxy, g_object_unref)
#endif

    void com_jsonite_daemon_calculator_proxy_new (
            GDBusConnection     *connection,
            GDBusProxyFlags      flags,
            const gchar         *name,
            const gchar         *object_path,
            GCancellable        *cancellable,
            GAsyncReadyCallback  callback,
            gpointer             user_data);
ComJsoniteDaemonCalculator *com_jsonite_daemon_calculator_proxy_new_finish (
        GAsyncResult        *res,
        GError             **error);
ComJsoniteDaemonCalculator *com_jsonite_daemon_calculator_proxy_new_sync (
        GDBusConnection     *connection,
        GDBusProxyFlags      flags,
        const gchar         *name,
        const gchar         *object_path,
        GCancellable        *cancellable,
        GError             **error);

void com_jsonite_daemon_calculator_proxy_new_for_bus (
        GBusType             bus_type,
        GDBusProxyFlags      flags,
        const gchar         *name,
        const gchar         *object_path,
        GCancellable        *cancellable,
        GAsyncReadyCallback  callback,
        gpointer             user_data);
ComJsoniteDaemonCalculator *com_jsonite_daemon_calculator_proxy_new_for_bus_finish (
        GAsyncResult        *res,
        GError             **error);
ComJsoniteDaemonCalculator *com_jsonite_daemon_calculator_proxy_new_for_bus_sync (
        GBusType             bus_type,
        GDBusProxyFlags      flags,
        const gchar         *name,
        const gchar         *object_path,
        GCancellable        *cancellable,
        GError             **error);


/* ---- */

#define TYPE_COM_JSONITE_DAEMON_CALCULATOR_SKELETON (com_jsonite_daemon_calculator_skeleton_get_type ())
#define COM_JSONITE_DAEMON_CALCULATOR_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_JSONITE_DAEMON_CALCULATOR_SKELETON, ComJsoniteDaemonCalculatorSkeleton))
#define COM_JSONITE_DAEMON_CALCULATOR_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_JSONITE_DAEMON_CALCULATOR_SKELETON, ComJsoniteDaemonCalculatorSkeletonClass))
#define COM_JSONITE_DAEMON_CALCULATOR_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_JSONITE_DAEMON_CALCULATOR_SKELETON, ComJsoniteDaemonCalculatorSkeletonClass))
#define IS_COM_JSONITE_DAEMON_CALCULATOR_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_JSONITE_DAEMON_CALCULATOR_SKELETON))
#define IS_COM_JSONITE_DAEMON_CALCULATOR_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_JSONITE_DAEMON_CALCULATOR_SKELETON))

typedef struct _ComJsoniteDaemonCalculatorSkeleton ComJsoniteDaemonCalculatorSkeleton;
typedef struct _ComJsoniteDaemonCalculatorSkeletonClass ComJsoniteDaemonCalculatorSkeletonClass;
typedef struct _ComJsoniteDaemonCalculatorSkeletonPrivate ComJsoniteDaemonCalculatorSkeletonPrivate;

struct _ComJsoniteDaemonCalculatorSkeleton
{
    /*< private >*/
    GDBusInterfaceSkeleton parent_instance;
    ComJsoniteDaemonCalculatorSkeletonPrivate *priv;
};

struct _ComJsoniteDaemonCalculatorSkeletonClass
{
    GDBusInterfaceSkeletonClass parent_class;
};

GType com_jsonite_daemon_calculator_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComJsoniteDaemonCalculatorSkeleton, g_object_unref)
#endif

    ComJsoniteDaemonCalculator *com_jsonite_daemon_calculator_skeleton_new (void);


    G_END_DECLS

#endif /* __GDBUS_CALCULATOR_H__ */
